[Fix] Pin release version
aws-ia/terraform-aws-polygon-technology-edge pull request #14
Opened 2022-10-21 15:02 UTC by ZeljkoBenovic

This PR pins the `polygon-edge` release version, as there are some breaking changes in the latest release which are incompatible with current deployment.

It also upgrades `aws-ia/vpc/aws` module version and fixes a minor bug with Lambda IAM security policy.

2022-10-25 21:03 UTC, sshvans commented
@ZeljkoBenovic Readme files are autogenerated. Any changes you want to make to readme should be done in header.md file. Please see [doc](https://aws-ia-us-west-2.s3.us-west-2.amazonaws.com/docs/content/index.html#/lessons/8rpYWWL59M7dcS-NsjYmaISUu-L_UqEv) for reference.

2022-10-25 21:03 UTC, sshvans requested changes
See comment

2022-10-31 09:58 UTC, ZeljkoBenovic commented
Fixed line endings. It should be good now.

Just one note. Pre-commit is having some issues with `aws-ia/vpc/aws` module:
```
TFLint in ./:
Failed to load configurations; .terraform/modules/vpc/variables.tf:186,36-51: Invalid type specification; Optional attribute modifier expects only one argument: the attribute type., and 3 other diagnostic(s):

Error: Invalid type specification

  on .terraform/modules/vpc/variables.tf line 186, in variable "vpc_flow_logs":
 186:     traffic_type         = optional(string, "ALL")

Optional attribute modifier expects only one argument: the attribute type.

Error: Invalid type specification

  on .terraform/modules/vpc/variables.tf line 188, in variable "vpc_flow_logs":
 188:       file_format                = optional(string, "plain-text")

Optional attribute modifier expects only one argument: the attribute type.

Error: Invalid type specification

  on .terraform/modules/vpc/variables.tf line 189, in variable "vpc_flow_logs":
 189:       hive_compatible_partitions = optional(bool, false)

Optional attribute modifier expects only one argument: the attribute type.

Error: Invalid type specification

  on .terraform/modules/vpc/variables.tf line 190, in variable "vpc_flow_logs":
 190:       per_hour_partition         = optional(bool, false)

Optional attribute modifier expects only one argument: the attribute type.
```

Tried adding `exclude` to `pre-commit`, but it won't work.

2022-11-07 21:37 UTC, sshvans approved these changes

2022-11-07 21:37 UTC, merged